/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestCreateShortanswerImport } from './routes/test-create-shortanswer'
import { Route as TestCreateMultiselectImport } from './routes/test-create-multiselect'
import { Route as QuizzesImport } from './routes/quizzes'
import { Route as ProfileImport } from './routes/profile'
import { Route as NotesImport } from './routes/notes'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'

// Create/Update Routes

const TestCreateShortanswerRoute = TestCreateShortanswerImport.update({
  id: '/test-create-shortanswer',
  path: '/test-create-shortanswer',
  getParentRoute: () => rootRoute,
} as any)

const TestCreateMultiselectRoute = TestCreateMultiselectImport.update({
  id: '/test-create-multiselect',
  path: '/test-create-multiselect',
  getParentRoute: () => rootRoute,
} as any)

const QuizzesRoute = QuizzesImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const NotesRoute = NotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesImport
      parentRoute: typeof rootRoute
    }
    '/test-create-multiselect': {
      id: '/test-create-multiselect'
      path: '/test-create-multiselect'
      fullPath: '/test-create-multiselect'
      preLoaderRoute: typeof TestCreateMultiselectImport
      parentRoute: typeof rootRoute
    }
    '/test-create-shortanswer': {
      id: '/test-create-shortanswer'
      path: '/test-create-shortanswer'
      fullPath: '/test-create-shortanswer'
      preLoaderRoute: typeof TestCreateShortanswerImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/quizzes': typeof QuizzesRoute
  '/test-create-multiselect': typeof TestCreateMultiselectRoute
  '/test-create-shortanswer': typeof TestCreateShortanswerRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/quizzes': typeof QuizzesRoute
  '/test-create-multiselect': typeof TestCreateMultiselectRoute
  '/test-create-shortanswer': typeof TestCreateShortanswerRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/quizzes': typeof QuizzesRoute
  '/test-create-multiselect': typeof TestCreateMultiselectRoute
  '/test-create-shortanswer': typeof TestCreateShortanswerRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/profile'
    | '/quizzes'
    | '/test-create-multiselect'
    | '/test-create-shortanswer'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/profile'
    | '/quizzes'
    | '/test-create-multiselect'
    | '/test-create-shortanswer'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/profile'
    | '/quizzes'
    | '/test-create-multiselect'
    | '/test-create-shortanswer'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRoute
  QuizzesRoute: typeof QuizzesRoute
  TestCreateMultiselectRoute: typeof TestCreateMultiselectRoute
  TestCreateShortanswerRoute: typeof TestCreateShortanswerRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  QuizzesRoute: QuizzesRoute,
  TestCreateMultiselectRoute: TestCreateMultiselectRoute,
  TestCreateShortanswerRoute: TestCreateShortanswerRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notes",
        "/profile",
        "/quizzes",
        "/test-create-multiselect",
        "/test-create-shortanswer",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/notes": {
      "filePath": "notes.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/quizzes": {
      "filePath": "quizzes.tsx"
    },
    "/test-create-multiselect": {
      "filePath": "test-create-multiselect.tsx"
    },
    "/test-create-shortanswer": {
      "filePath": "test-create-shortanswer.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
